/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/fps_animations_vsk.glb 
Author: Cransh (https://sketchfab.com/ccransh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fps-animations-vsk-191e34e043d546718d9e899d19d2f974
Title: FPS animations VSK
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/fps_animations_vsk.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="209b00474e374bfe99088b001d708629fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Male_04_Animation_Ready" scale={103.608} />
                <group name="Rig" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_8" scale={103.608} />
                    <group name="Object_66" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
                    <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Male_04_Animation_Ready.001']} skeleton={nodes.Object_9.skeleton} />
                    <skinnedMesh name="Object_67" geometry={nodes.Object_67.geometry} material={materials.Magcover} skeleton={nodes.Object_67.skeleton} />
                    <skinnedMesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials['Stock-silencer']} skeleton={nodes.Object_68.skeleton} />
                    <skinnedMesh name="Object_69" geometry={nodes.Object_69.geometry} material={materials.Main_body} skeleton={nodes.Object_69.skeleton} />
                  </group>
                </group>
                <group name="VSK-94" rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fps_animations_vsk.glb')
